# Auto-generated by /Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace/BaseTools
fi
if [ -e /Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace/BaseTools/Bin/Darwin-x86_64 ]
then
  if [ ${PATH//Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace/BaseTools/Bin/Darwin-x86_64/} == $PATH ]
  then
    export PATH=/Users/g5/Documents/GitHub/next-loader/src/edk2/UDK2018/MyWorkSpace/BaseTools/Bin/Darwin-x86_64:$PATH
  fi
fi
